version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - run: pwd
  deploy:
    docker:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: scp -r ~/laravel/* serveradmin%brooklynrail.org@brooklynrail.org:~/domains/circleci.brooklynrail.org/html/
      - run:
          name: Test SSH
          command: |
            ssh serveradmin%brooklynrail.org@brooklynrail.org "touch ~/domains/circleci.brooklynrail.org/html/test.txt"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
